In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('metrics_data.csv', index_col='_id')
person = pd.read_csv('../person.csv', index_col='_id')

In [3]:
person

     height  mass  position  is_valid  age  sex
_id
1       180    85         2         0   18    1
2       185    75         1         0   18    1
3       185    75         2         0   18    1
6       185    75         3         0   18    1
7       185    75         1         1   18    1
..      ...   ...       ...       ...  ...  ...
307     170    61         2         0   20    0
308     170    61         3         0   20    0
309     170    61         1         1   20    0
310     170    61         2         1   20    0
311     170    61         3         1   20    0

[128 rows x 6 columns]

In [4]:
data

,x_mean,x_std,x_max,x_min,y_mean,y_std,y_max,y_min,z_mean,z_std,...,sma,x_energy,y_energy,z_energy,x_iqr,y_iqr,z_iqr,xy_corr,xz_corr,yz_corr
_id,,,,,,,,,,,,,,,,,,,,,
1,13110.861519,1489.074033,17584.0,628.0,-231.045310,1249.368959,3960.0,-5076.0,-9781.608168,1204.070214,...,16514.114425,1.741106e+08,1.613309e+06,9.712872e+07,684.0,1788.0,808.0,0.389405,0.895658,0.367969
2,10398.993311,636.795316,11924.0,8728.0,1220.230769,712.538755,3100.0,-1344.0,-12743.739130,516.853783,...,16528.702152,1.085442e+08,1.996250e+06,1.626698e+08,1136.0,735.0,866.0,-0.186981,0.950490,-0.062792
3,12969.669749,807.711275,15236.0,10760.0,-36.354029,1327.785100,4640.0,-5000.0,-10092.491413,1051.603116,...,16538.716131,1.688639e+08,1.762006e+06,1.029628e+08,1164.0,964.0,1368.0,-0.023526,0.921424,-0.023458
6,12765.113725,3289.505788,29072.0,6396.0,815.027451,2927.223542,12488.0,-5844.0,-10411.811765,3428.969363,...,16912.948421,1.737265e+08,9.199305e+06,1.201175e+08,3768.0,3326.0,4846.0,0.078659,-0.394979,-0.021597
7,15146.131868,160.385778,16424.0,12984.0,-1865.611722,122.331084,-1588.0,-3500.0,-6243.567766,290.745677,...,16491.939761,2.294310e+08,3.495458e+06,3.906659e+07,196.0,132.0,485.0,-0.203383,0.750925,-0.452449
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307,15784.175413,291.910508,17200.0,14204.0,-675.847592,819.859282,3412.0,-2132.0,-4900.934579,647.924670,...,16576.112392,2.492253e+08,1.128456e+06,2.443866e+07,220.0,1152.0,582.0,-0.147803,0.830312,-0.258740
308,15282.539857,3387.421937,27404.0,8024.0,-610.390324,1745.136557,5224.0,-6856.0,-6231.296317,2841.199185,...,16739.117563,2.450243e+08,3.416404e+06,4.689703e+07,5468.0,2342.0,4200.0,-0.051417,-0.568697,0.066659
309,14337.600584,197.941923,15764.0,12352.0,-675.310697,332.853723,928.0,-4060.0,-8232.575392,279.984006,...,16553.440474,2.056060e+08,5.667957e+05,6.785366e+07,164.0,264.0,264.0,0.213569,0.786830,0.045659
310,15800.594937,261.708128,18100.0,13532.0,-641.810127,539.895303,2432.0,-2792.0,-4761.094937,501.641510,...,16532.446911,2.497273e+08,7.032919e+05,2.291957e+07,244.0,548.0,633.0,0.137097,0.777612,0.054161
311,14979.542553,3330.229010,25580.0,8564.0,-920.540426,1479.689278,3804.0,-5468.0,-7088.687234,2260.904692,...,16737.274273,2.354712e+08,3.035710e+06,5.535846e+07,5563.0,1872.0,3933.0,-0.094261,-0.571363,0.015300

### Возьмем метрики из прямого сидячего положения и добавим их к остальным метрикам (кроме самого прямого сидячего положения.

In [19]:
added_idx = person[(person['position'] == 1) & (person['is_valid'] == 1)].index
rest_idx = person[~((person['position'] == 1) & (person['is_valid'] == 1))].index

In [20]:
added_person = person.loc[added_idx].copy()
rest_person = person.loc[rest_idx].copy()

In [21]:
id_cols = ['height', 'mass', 'age', 'sex']

In [22]:
new_data = pd.DataFrame()
added_col_names = list(map(lambda x: x + '_pos1', data.columns))

In [23]:
for added_idx, x in added_person[id_cols].iterrows():
    rest_idx = rest_person[np.all(rest_person[id_cols] == x, axis=1)].index
    
    added_row = data.loc[added_idx]
    rest_rows = data.loc[rest_idx]
    rest_rows[added_col_names] = added_row
    
    new_data = pd.concat([new_data, rest_rows])

In [24]:
new_data

,x_mean,x_std,x_max,x_min,y_mean,y_std,y_max,y_min,z_mean,z_std,...,sma_pos1,x_energy_pos1,y_energy_pos1,z_energy_pos1,x_iqr_pos1,y_iqr_pos1,z_iqr_pos1,xy_corr_pos1,xz_corr_pos1,yz_corr_pos1
_id,,,,,,,,,,,,,,,,,,,,,
2,10398.993311,636.795316,11924.0,8728.0,1220.230769,712.538755,3100.0,-1344.0,-12743.739130,516.853783,...,16491.939761,2.294310e+08,3.495458e+06,3.906659e+07,196.0,132.0,485.0,-0.203383,0.750925,-0.452449
3,12969.669749,807.711275,15236.0,10760.0,-36.354029,1327.785100,4640.0,-5000.0,-10092.491413,1051.603116,...,16491.939761,2.294310e+08,3.495458e+06,3.906659e+07,196.0,132.0,485.0,-0.203383,0.750925,-0.452449
6,12765.113725,3289.505788,29072.0,6396.0,815.027451,2927.223542,12488.0,-5844.0,-10411.811765,3428.969363,...,16491.939761,2.294310e+08,3.495458e+06,3.906659e+07,196.0,132.0,485.0,-0.203383,0.750925,-0.452449
8,15474.915254,261.281890,16056.0,13444.0,-1894.415254,442.980129,956.0,-4544.0,-5328.025424,548.266501,...,16491.939761,2.294310e+08,3.495458e+06,3.906659e+07,196.0,132.0,485.0,-0.203383,0.750925,-0.452449
9,15071.435323,3140.794595,29164.0,10240.0,-1579.159204,1482.553175,3308.0,-7412.0,-6577.519900,1970.134951,...,16491.939761,2.294310e+08,3.495458e+06,3.906659e+07,196.0,132.0,485.0,-0.203383,0.750925,-0.452449
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,12161.324964,245.637725,13448.0,11444.0,-1218.740705,446.575814,1068.0,-3576.0,-11237.724771,302.630834,...,16553.440474,2.056060e+08,5.667957e+05,6.785366e+07,164.0,264.0,264.0,0.213569,0.786830,0.045659
307,15784.175413,291.910508,17200.0,14204.0,-675.847592,819.859282,3412.0,-2132.0,-4900.934579,647.924670,...,16553.440474,2.056060e+08,5.667957e+05,6.785366e+07,164.0,264.0,264.0,0.213569,0.786830,0.045659
308,15282.539857,3387.421937,27404.0,8024.0,-610.390324,1745.136557,5224.0,-6856.0,-6231.296317,2841.199185,...,16553.440474,2.056060e+08,5.667957e+05,6.785366e+07,164.0,264.0,264.0,0.213569,0.786830,0.045659
310,15800.594937,261.708128,18100.0,13532.0,-641.810127,539.895303,2432.0,-2792.0,-4761.094937,501.641510,...,16553.440474,2.056060e+08,5.667957e+05,6.785366e+07,164.0,264.0,264.0,0.213569,0.786830,0.045659
311,14979.542553,3330.229010,25580.0,8564.0,-920.540426,1479.689278,3804.0,-5468.0,-7088.687234,2260.904692,...,16553.440474,2.056060e+08,5.667957e+05,6.785366e+07,164.0,264.0,264.0,0.213569,0.786830,0.045659

In [13]:
rest_person = rest_person.drop(1, axis=0)

In [14]:
new_data.to_csv('added_pos1_metrics_data.csv')
rest_person.to_csv('added_pos1_metrics_person.csv')

### Для оконных данных

In [3]:
data = pd.read_csv('metrics_data.csv', index_col='_id')
person = pd.read_csv('../person.csv', index_col='_id')
windowed_data = pd.read_csv('windowed_metrics_data.csv', index_col=[0, 1])

In [4]:
added_idx = person[(person['position'] == 1) & (person['is_valid'] == 1)].index
rest_idx = person[~((person['position'] == 1) & (person['is_valid'] == 1))].index

added_person = person.loc[added_idx].copy()
rest_person = person.loc[rest_idx].copy()

In [5]:
id_cols = ['height', 'mass', 'age', 'sex']

In [27]:
added_data = pd.DataFrame()
added_col_names = list(map(lambda x: x + '_pos1', data.columns))

In [28]:
for added_idx, x in added_person[id_cols].iterrows():
    idx = person[np.all(person[id_cols] == x, axis=1)].index
    
    added_row = data.loc[added_idx]
    rows = data.loc[idx]
    rows[added_col_names] = added_row
    
    added_data = pd.concat([added_data, rows])
    
added_data = added_data.iloc[::,22:]

In [30]:
added_data = pd.concat([added_data, person], axis=1)

In [32]:
new_data = pd.concat([windowed_data.reset_index(level=1), added_data], axis=1)\
                .dropna()\
                .set_index('level_1', append=True)

In [33]:
new_data

               x_mean        x_std    x_max    x_min      x_energy   x_iqr  \
_id level_1
2   1673     11156.76   123.532772  11380.0  10836.0  1.244884e+08   177.0
    1698     11156.88   128.858961  11380.0  10836.0  1.244924e+08   193.0
    1723     11154.36   134.410311  11532.0  10836.0  1.244376e+08   190.0
    1748     10998.28   415.506022  11532.0   9384.0  1.211331e+08   323.0
    1773     10883.04   409.575930  11532.0   9384.0  1.186066e+08   543.0
...               ...          ...      ...      ...           ...     ...
311 248547   14922.72  3592.622199  23688.0   9424.0  2.354654e+08  5910.0
    248572   14993.44  3544.279603  23688.0   9424.0  2.372395e+08  5291.0
    248597   15152.04  3581.770072  23688.0   9212.0  2.422851e+08  5213.0
    248622   14821.28  3600.001207  24076.0   9212.0  2.325007e+08  5696.0
    248647   15011.96  3451.862399  24076.0   9212.0  2.371551e+08  4856.0

              y_mean        y_std   y_max   y_min  ...  z_iqr_pos1  \
_id level_1                                        ...
2   1673     1158.80    73.172275  1348.0   920.0  ...       485.0
    1698     1137.96    69.416023  1300.0   920.0  ...       485.0
    1723     1088.32   171.829072  1380.0   164.0  ...       485.0
    1748      853.36   499.190851  1380.0 -1032.0  ...       485.0
    1773      537.68   622.192456  1380.0 -1032.0  ...       485.0
...              ...          ...     ...     ...  ...         ...
311 248547   -895.72  1385.373319  3096.0 -3980.0  ...       264.0
    248572  -1130.24  1549.973927  3096.0 -4504.0  ...       264.0
    248597   -994.12  1720.060648  3168.0 -4504.0  ...       264.0
    248622   -948.92  1772.984961  3760.0 -5212.0  ...       264.0
    248647   -943.04  1763.129185  3760.0 -5212.0  ...       264.0

             xy_corr_pos1  xz_corr_pos1  yz_corr_pos1  height  mass  position  \
_id level_1
2   1673        -0.203383      0.750925     -0.452449     185    75         1
    1698        -0.203383      0.750925     -0.452449     185    75         1
    1723        -0.203383      0.750925     -0.452449     185    75         1
    1748        -0.203383      0.750925     -0.452449     185    75         1
    1773        -0.203383      0.750925     -0.452449     185    75         1
...                   ...           ...           ...     ...   ...       ...
311 248547       0.213569      0.786830      0.045659     170    61         3
    248572       0.213569      0.786830      0.045659     170    61         3
    248597       0.213569      0.786830      0.045659     170    61         3
    248622       0.213569      0.786830      0.045659     170    61         3
    248647       0.213569      0.786830      0.045659     170    61         3

             is_valid  age  sex
_id level_1
2   1673            0   18    1
    1698            0   18    1
    1723            0   18    1
    1748            0   18    1
    1773            0   18    1
...               ...  ...  ...
311 248547          1   20    0
    248572          1   20    0
    248597          1   20    0
    248622          1   20    0
    248647          1   20    0

[9381 rows x 50 columns]

In [34]:
new_data.to_csv('added_pos1_metrics_windowed.csv')

### Для разных оконных значений

In [1]:
window_sizes = [50, 100, 150, 200]

In [ ]:
data = pd.read_csv('metrics_data.csv', index_col='_id')
person = pd.read_csv('../person.csv', index_col='_id')

load_path = 'data_windowed.csv'
windowed_data = pd.read_csv('windowed_metrics_data.csv', index_col=[0, 1])